version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: conf
    versions:
    - 9.0.0
    - 9.0.1
    - 9.0.2
  - dependency-name: ora
    versions:
    - 5.3.0
